title: nx-displaygrid
views:
    - title: nx-displaygrid
      path: nx-displaygrid
      icon: mdi:calendar-multiselect
      panel: true

      cards:
          - type: custom:nx-displaygrid
            title: nx-displaygrid
            debug: false

            # Layout tuning
            <<: !include ../includes/nx_displaygrid_layout.yaml

            # People palette
            people: !include ../includes/nx_displaygrid_people.yaml

            calendars: !include ../includes/nx_displaygrid_calendars.yaml

            todos: !include ../includes/nx_displaygrid_todos.yaml

            shopping: !include ../includes/nx_displaygrid_shopping.yaml

            # Home controls: entities shown on Home Controls screen
            home_controls: !include ../includes/home_controls.yaml
