default_config:

homeassistant:
    packages: !include packages/_packages.yaml

lovelace:
    resource_mode: yaml

    resources: !include lovelace/resources.yaml

    dashboards:
        nx-family-dashboard:
            mode: yaml
            title: NX - Family Dashboard
            icon: mdi:account-group
            show_in_sidebar: true
            require_admin: false
            filename: lovelace/nx-family-dashboard.yaml

nx_displaygrid:
